#!/bin/bash

# Compile
ant

# Edit these settings to match your system
CHECKSTYLE_HOME=~/checkstyle-7.5.1

java -cp $CHECKSTYLE_HOME/\* com.puppycrawl.tools.checkstyle.Main -c checkstyle.xml com/horstmann/violet/*.java
